export const SET_PLAYER_VIDEO = 'SET_PLAYER_VIDEO'

export const SET_GUESS_LIKE_LIST = 'SET_GUESS_LIKE_LIST'

export const SET_GUESS_LIKE_PAGE_NUM = 'SET_GUESS_LIKE_PAGE_NUM'

export const SET_GUESS_LIKE_HAS_MORE = 'SET_GUESS_LIKE_HAS_MORE'

export const SET_ROUTER_TITLE = 'SET_ROUTER_TITLE'

export const SET_VIDEO_TYPES = 'SET_VIDEO_TYPES'

export const SET_RECOMMEND_VIDEO_LIST = 'SET_RECOMMEND_VIDEO_LIST'

export const SET_QQ = 'SET_QQ'

export const SET_WECHAT = 'SET_WECHAT'

export const SET_FAVORITELIST = 'SET_FAVORITELIST'
